#
#
# This file was autogenerated by python_on_wheels.
# But YOU CAN EDIT THIS FILE SAFELY
# It will not be overwtitten by python_on_wheels
# unless you force it with the -f or --force option
# 

# date created:     2012-06-20
import sys,os

sys.path.append( os.path.abspath(os.path.join( os.path.dirname(os.path.abspath(__file__)), "../lib" )))
sys.path.append( os.path.abspath(os.path.join( os.path.dirname(os.path.abspath(__file__)), "./basemodels" )))

import powlib
import BaseAtestmodel

class Atestmodel(BaseAtestmodel.BaseAtestmodel):
    #
    # Class: Atestmodel
    #
    pass
