#
#
# This file was autogenerated by python_on_wheels.
# But YOU CAN EDIT THIS FILE SAFELY
# It will not be overwtitten by python_on_wheels
# unless you force it with the -f or --force option
# 

# date created: 	2011-06-25

from sqlalchemy import *
from sqlalchemy.schema import CreateTable
from sqlalchemy import event, DDL
import sys
import os

sys.path.append( os.path.abspath(os.path.join( os.path.dirname(os.path.abspath(__file__)), "../lib" )))
sys.path.append( os.path.abspath(os.path.join( os.path.dirname(os.path.abspath(__file__)), "../models" )))
import powlib
from PowTable import PowTable
from BaseMigration import BaseMigration
import User

class Migration(BaseMigration):
	table_name="comments"
	table = None
		
	def up(self):
			#
			# here is where you define your table (Format see example below)
			# the columns below are just examples.
			# Remember that PoW automatically adds an id and a timestamp column (ID,TIMESTAMP)
		self.table = PowTable(self.table_name, self.__metadata__,
			Column('title', String(50)),
			Column('content', String(50)),
			Column('post_id', Integer, ForeignKey('posts.id'))
		)
		#self.create_table()
		
		user = User.User()
		create_table_ddl = DDL(str(CreateTable(user.__table__)))
		print str(CreateTable(user.__table__))
		
		#self.getEngine().connect().execute(create_table_ddl)
		
	def down(self):
		self.drop_table()
